//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "room_scope_type_enum"
)]
pub enum RoomScopeTypeEnum {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "strict")]
    Strict,
}
