[package]
name = "redis"
version = "0.1.0"
edition = "2024"
homepage.workspace = true

[dependencies]
common = { version = "0.1.0", path = "../common" }
deadpool-redis = { version = "0.21.1", features = ["rt_tokio_1", "serde"] }
serde = "1.0.219"
serde_json = "1.0.140"
